version: '3.9'

services:
  api-rest:
    image: api-rest
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: api_rest_database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bdTren
      MYSQL_USER: anthonny
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume: